### ISSUE TITLE
BOWKMeansTrainer cannot be created.

### ISSUE THREAD

**Issue by korhun** [shimat/opencvsharp#287]
Following exception occurs on this line:
` BOWKMeansTrainer test = new BOWKMeansTrainer(100);`

> System.EntryPointNotFoundException occurred
  HResult=-2146233053
  Message=Unable to find an entry point named 'features2d_BOWKMeansTrainer_new' in DLL 'OpenCvSharpExtern'.
  Source=OpenCvSharp
  TypeName=""
  StackTrace:
       at OpenCvSharp.NativeMethods.features2d_BOWKMeansTrainer_new(Int32 clusterCount, TermCriteria termcrit, Int32 attempts, Int32 flags)
       at OpenCvSharp.BOWKMeansTrainer..ctor(Int32 clusterCount, Nullable`1 termcrit, Int32 attempts, KMeansFlags flags)
       at BOW_Test.Categorizer3..ctor() in C:\Projects\BOW_Test\Categorizer3.cs:line 66
  InnerException:

**Comment by shimat** [comment]
Thanks 👍  This bug is fixed in the next release. The BOWKMeansTrainer wrapper is not compiled.
https://github.com/shimat/opencvsharp/commit/95976675a80eda28dc4fa6491b85b838b14350fc#diff-2da67aa2f12a93b56769e2acb18efcbbR4

**Comment by korhun** [comment]
Thank you very much. Have you committed to git? If not, is there any other way that I could get this update?
I have tried to pull the latest git files and compile the projects; then tried with those dll's. However on this line:
`SURF.Create(500)`
 I get this error (it is a handled error though, this surf instance seems to be created):
>  System.Exception occurred
>   HResult=-2146233088
>   Message=Failed to find dll "OpenCvSharpExtern", for processor architecture AMD64.
>   Source=OpenCvSharp
>   StackTrace:
>        at OpenCvSharp.Util.WindowsLibraryLoader.LoadLibrary(String dllName, IEnumerable`1 additionalPaths) in C:\opencvsharp\src\OpenCvSharp\Util\WindowsLibraryLoader.cs:line 183
>   InnerException: 

Also BOWKMeansTrainer still cannot be created.

**Comment by korhun** [comment]
When will the next release be published?

**Comment by korhun** [comment]
I get the same error in 3.2 (26 Jan., 2017) release. 

https://github.com/shimat/opencvsharp/issues/295
